research_task:
  description: >
    Effectue une recherche approfondie et complète sur le sujet "{topic}", en incluant les publications les plus récentes, les discours des acteurs clés (ONU, gouvernements, ONG), ainsi que les données statistiques pertinentes.
  expected_output: >
    Une liste de 10 ressources web soigneusement sélectionnées avec : titre, lien, date et résumé critique en une ou deux phrases expliquant l'importance spécifique de chaque source dans le cadre du sujet "{topic}".
  agent: researcher

cheat_sheet_task:
  description: >
    Rédige une fiche de synthèse extrêmement claire et structurée sur le sujet "{topic}" en format markdown, incluant une définition concise, le contexte historique, les principaux enjeux contemporains et les acteurs clés impliqués.
  expected_output: >
    Une cheat sheet complète en markdown organisée sous les titres : "Définition du sujet", "Historique rapide", "Enjeux principaux", "Acteurs clés et leurs rôles".
  agent: researcher

position_summary_task:
  description: >
    Prépare une fiche détaillée mais concise résumant précisément et fidèlement la position officielle du pays "{country}" sur le sujet "{topic}". Inclut des exemples récents de déclarations officielles, votes à l’ONU, et tout document de référence essentiel.
  expected_output: >
    Une fiche récapitulative en markdown structurée clairement sous les titres : "Position officielle générale", "Intérêts spécifiques du pays", "Actions et déclarations récentes", "Alliances et adversaires stratégiques".
  agent: country_specialist
